version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: ghost_db
    restart: always
    environment:
      POSTGRES_USER: ghost
      POSTGRES_PASSWORD: ghostpass
      POSTGRES_DB: ghost
    ports:
      - "5436:5436"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: ghost_api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://ghost:ghostpass@db:5436/ghost
    depends_on:
      - db

volumes:
  pgdata: